build:
  image: bjodah/bjodahimg16:v1.2
  environment:
    - PYNLEQ2_NLEQ2_ROOT_URL=$$PYNLEQ2_NLEQ2_ROOT_URL
  commands:
    - (cd /; python2 -m pip install --user pynleq2)
    - (cd /; python3 -m pip install --user pynleq2)
    - export PYNLEQ2_NLEQ2_ROOT_URL=""
    - ./scripts/ci.sh pyneqsys
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: pyneqsys
    source: deploy/
    target: ~
    recursive: true
    delete: false
