when:
  - event: [push]

steps:
  - name: build
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:24
    environment:
      CC: gcc
      CXX: g++
      FC: gfortran
    commands:
      #- export PYNLEQ2_NLEQ2_ROOT_URL=""
      #- (cd /; python3 -m pip install --user pynleq2)
      - ./scripts/ci.sh pyneqsys
      - ./scripts/prepare_deploy.sh
