{% set name = "pyneqsys" %}
{% set version = GIT_DESCRIBE_TAG | replace("v", "") %}
{% set number = GIT_DESCRIBE_NUMBER | int %}
{% if number > 0 %}
   {% set version = version + ".post" + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy >1.7
    - scipy >=0.19.1
    - sym >=0.3.1
    - sympy >=1.1.1,!=1.2
    - matplotlib >=2.0.2

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    - python-symengine
    - symcxx
    - pysym
    - pykinsol
    - ipopt
    - levmar
  commands:
    - pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Solve symbolically defined systems of non-linear equations numerically.'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
